version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION
      - REPOSITORY_URI = 034362031980.dkr.ecr.us-east-1.amazonaws.com/aime-chatbot
  build:
    commands:
      - echo Build started on `date`
      - echo Cloning the code from GitHub...
      - git clone https://github.com/scottalanturner/ai_me.git
      - cd your-repo
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

